export const SAMPLE_ATTACHMENT_LIST = [
  {
    title: 'Sample Document 1',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'application/pdf',
    uploadedBy: 'John Doe',
  },
  {
    title: 'Sample Image 1',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'image/jpeg',
    uploadedBy: 'Jane Smith',
  },
  {
    title: 'Sample Presentation',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'application/vnd.ms-powerpoint',
    uploadedBy: 'Alice Johnson',
  },
  {
    title: 'Sample Spreadsheet',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'application/vnd.ms-excel',
    uploadedBy: 'Bob Brown',
  },
  {
    title: 'Sample Video',
    url: 'https://www.youtube.com/watch?v=MKaVEsaEWRE&list=RDMKaVEsaEWRE&start_radio=1',
    date: '2024-02-27',
    mimeType: 'video/mp4',
    uploadedBy: 'Eva Wilson',
  },
  {
    title: 'Sample File 1',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'application/octet-stream',
    uploadedBy: 'Michael Lee',
  },
  {
    title: 'Sample Document 2',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'application/pdf',
    uploadedBy: 'Sara Martinez',
  },
  {
    title: 'Sample Image 2',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'image/jpeg',
    uploadedBy: 'David Wilson',
  },
  {
    title: 'Sample File 2',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'application/octet-stream',
    uploadedBy: 'Emily Johnson',
  },
  {
    title: 'Sample Audio',
    url: 'https://www.alleycat.org/wp-content/uploads/2019/03/FELV-cat.jpg',
    date: '2024-02-27',
    mimeType: 'audio/mpeg',
    uploadedBy: 'Olivia Brown',
  },
];
